import comp1 from '../assets/images/comp1.png'
import comp2 from '../assets/images/comp2.png'
import React, { useState, useEffect } from "react";
import { images } from '../constants';
 const waterCompanies = [
    {
      id: 1,
      name: "PureFlow Water Services",
      logo: comp1,
      image: "https://dummyimage.com/600x400/4A90E2/ffffff&text=PureFlow+Water+Truck",
      waterCarsAvailable: 5,
      location: "Accra, Ghana",
    },
    {
      id: 2,
      name: "AquaFresh Supply",
      logo: comp2,
      image: "https://dummyimage.com/600x400/FF5733/ffffff&text=AquaFresh+Water+Truck",
      waterCarsAvailable: 0,
      location: "Kumasi, Ghana",
    },
    {
      id: 3,
      name: "BlueWave Hydration",
      logo: comp1,
      image: "https://dummyimage.com/600x400/3498DB/ffffff&text=BlueWave+Truck",
      waterCarsAvailable: 7,
      location: "Takoradi, Ghana",
    },
    {
      id: 4,
      name: "Crystal Clear Distributors",
      logo: comp1,
      image: "https://dummyimage.com/600x400/58D68D/ffffff&text=Crystal+Clear+Truck",
      waterCarsAvailable: 2,
      location: "Tamale, Ghana",
    },
    {
      id: 5,
      name: "FreshWave Waters",
      logo: comp2,
      image: "https://dummyimage.com/600x400/5DADE2/ffffff&text=FreshWave+Truck",
      waterCarsAvailable: 6,
      location: "Tema, Ghana",
    },
    {
      id: 6,
      name: "FreshWave Waters",
      logo: comp2,
      image: "https://dummyimage.com/600x400/5DADE2/ffffff&text=FreshWave+Truck",
      waterCarsAvailable: 6,
      location: "Tema, Ghana",
    },
    {
      id: 7,
      name: "FreshWave Waters",
      logo: comp2,
      image: "https://dummyimage.com/600x400/5DADE2/ffffff&text=FreshWave+Truck",
      waterCarsAvailable: 6,
      location: "Tema, Ghana",
    },
    {
        id: 8,
        name: "BlueWave Hydration",
        logo: comp1,
        image: "https://dummyimage.com/600x400/3498DB/ffffff&text=BlueWave+Truck",
        waterCarsAvailable: 7,
        location: "Takoradi, Ghana",
      },
  ];


export const pickups = [
  {
    id: 1,
    name: "PureFlow Water Services",
    logo: comp1,
    location: "Accra, Ghana",
    date: "2024-11-15",
    time: "10:00 AM",
    price: "50",
    status: "completed",
  },
  {
    id: 2,
    name: "AquaFresh Supply",
    logo: comp2,
    location: "Kumasi, Ghana",
    date: "2024-11-16",
    time: "2:30 PM",
    price: "45",
    status: "pending",
  },
  {
    id: 3,
    name: "BlueWave Hydration",
    logo: comp1,
    location: "Takoradi, Ghana",
    date: "2024-11-15",
    time: "9:00 AM",
    price: "60",
    status: "denied",
  },
  {
    id: 4,
    name: "Crystal Clear Distributors",
    logo: comp1,
    location: "Tamale, Ghana",
    date: "2024-11-17",
    time: "11:45 AM",
    price: "55",
    status: "ongoing",
  },
  {
    id: 5,
    name: "FreshWave Waters",
    logo: comp2,
    location: "Tema, Ghana",
    date: "2024-11-14",
    time: "3:00 PM",
    price: "40",
    status: "accepted",
  },
  {
    id: 6,
    name: "HydroPure Dispensers",
    logo: comp2,
    location: "Cape Coast, Ghana",
    date: "2024-11-15",
    time: "12:30 PM",
    price: "65",
    status: "completed",
  },
  {
    id: 7,
    name: "CleanWave Services",
    logo: comp1,
    location: "Ho, Ghana",
    date: "2024-11-18",
    time: "8:30 AM",
    price: "50",
    status: "pending",
  },
  {
    id: 8,
    name: "ClearH2O Delivery",
    logo: comp1,
    location: "Sunyani, Ghana",
    date: "2024-11-19",
    time: "1:15 PM",
    price: "48",
    status: "denied",
  },
  {
    id: 9,
    name: "SwiftWater Supplies",
    logo: comp2,
    location: "Bolgatanga, Ghana",
    date: "2024-11-20",
    time: "10:15 AM",
    price: "52",
    status: "ongoing",
  },
  {
    id: 10,
    name: "WavePure Hydration",
    logo: comp1,
    location: "Wa, Ghana",
    date: "2024-11-14",
    time: "5:30 PM",
    price: "38",
    status: "accepted",
  },
];
export const drivers = [
  {
    id: 1,
    name: "John Doe",
    image: comp1,
    timeDifference: "5",
    percentage: 45,
  },
  {
    id: 2,
    name: "Jane Smith",
    image: comp1,
    timeDifference: "2",
    percentage: 80,
  },
  {
    id: 3,
    name: "Michael Johnson",
    image: comp1,
    timeDifference: "10",
    percentage: 25,
  },
  {
    id: 4,
    name: "Emily Davis",
    image: comp1,
    timeDifference: "7",
    percentage: 60,
  },
  {
    id: 5,
    name: "Chris Brown",
    image:comp1,
    timeDifference: "3",
    percentage: 90,
  },
];




export default waterCompanies;